name: Optimize Images
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run optimization
    runs-on: ubuntu-latest
    steps:
      - uses: 9sako6/imgcmp@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

